watch_dir: "C:\Users\sdumbre\OneDrive - MORNINGSTAR INC\Documents\GitHub\Python-Projects\Smart-file-organiser\tests\test_watch" #Folder where all incoming files are watched
dest_root: "C:\Users\sdumbre\OneDrive - MORNINGSTAR INC\Documents\GitHub\Python-Projects\Smart-file-organiser\tests\test_sorted" #Root folder where files will be sorted
dry_run: true
conflict: "rename"
rules:
  - name: "Images"
    pattern: "\\.(jpg|jpeg|png|gif|heic)$"
    dest: "Images"
  - name: "Videos"
    pattern: "\\.(mp4|mov|mkv|avi)$"
    dest: "Videos"
  - name: "Docs"
    pattern: "\\.(pdf|docx?|xlsx?|pptx?)$"
    dest: "Documents"
  - name: "Archives"
    pattern: "\\.(zip|tar|gz|7z)$"
    dest: "Archives"
default_dest: "Others"
