watch_dir: "D:/Photos/Malvan/Enhanced/test_watch"
output_dir: "D:/Photos/Malvan/Enhanced/test_sorted"

rules:
  - name: Images
    extensions: [".jpg", ".jpeg", ".png", ".gif"]

  - name: Videos
    extensions: [".mp4", ".mkv", ".avi"]

  - name: Documents
    extensions: [".pdf", ".docx", ".txt"]
